// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function Backspace():Promise<app.State>;

export function ClearANSIColors():Promise<app.State>;

export function ClearRegion(arg1:number,arg2:number,arg3:number,arg4:number):Promise<app.State>;

export function ClearScreen():Promise<app.State>;

export function CopyBuffer():Promise<void>;

export function CopyRegion(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function Delete():Promise<app.State>;

export function DrawLineDown(arg1:string):Promise<app.State>;

export function DrawLineLeft(arg1:string):Promise<app.State>;

export function DrawLineRight(arg1:string):Promise<app.State>;

export function DrawLineUp(arg1:string):Promise<app.State>;

export function Enter():Promise<app.State>;

export function FillRegion(arg1:number,arg2:number,arg3:number,arg4:number,arg5:string):Promise<app.State>;

export function InsertText(arg1:string):Promise<app.State>;

export function MoveBottom():Promise<app.State>;

export function MoveDown():Promise<app.State>;

export function MoveEnd():Promise<app.State>;

export function MoveHome():Promise<app.State>;

export function MoveLeft():Promise<app.State>;

export function MoveRight():Promise<app.State>;

export function MoveTop():Promise<app.State>;

export function MoveUp():Promise<app.State>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<app.State>;

export function OpenFileDialog():Promise<app.FileActionResult>;

export function PasteFromClipboard():Promise<app.State>;

export function Save():Promise<app.FileActionResult>;

export function SaveAsDialog():Promise<app.FileActionResult>;

export function SaveFile(arg1:string):Promise<void>;

export function SetActiveANSIBGColor(arg1:string):Promise<void>;

export function SetActiveANSIColor(arg1:string):Promise<void>;

export function SetActiveANSIFGColor(arg1:string):Promise<void>;

export function SetCursor(arg1:number,arg2:number):Promise<app.State>;

export function SetRegionBGColor(arg1:number,arg2:number,arg3:number,arg4:number,arg5:string):Promise<app.State>;

export function SetRegionColor(arg1:number,arg2:number,arg3:number,arg4:number,arg5:string):Promise<app.State>;

export function Snapshot():Promise<app.State>;
