// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backspace() {
  return window['go']['app']['Bridge']['Backspace']();
}

export function ClearANSIColors() {
  return window['go']['app']['Bridge']['ClearANSIColors']();
}

export function ClearRegion(arg1, arg2, arg3, arg4) {
  return window['go']['app']['Bridge']['ClearRegion'](arg1, arg2, arg3, arg4);
}

export function ClearScreen() {
  return window['go']['app']['Bridge']['ClearScreen']();
}

export function CopyBuffer() {
  return window['go']['app']['Bridge']['CopyBuffer']();
}

export function CopyRegion(arg1, arg2, arg3, arg4) {
  return window['go']['app']['Bridge']['CopyRegion'](arg1, arg2, arg3, arg4);
}

export function Delete() {
  return window['go']['app']['Bridge']['Delete']();
}

export function DrawLineDown(arg1) {
  return window['go']['app']['Bridge']['DrawLineDown'](arg1);
}

export function DrawLineLeft(arg1) {
  return window['go']['app']['Bridge']['DrawLineLeft'](arg1);
}

export function DrawLineRight(arg1) {
  return window['go']['app']['Bridge']['DrawLineRight'](arg1);
}

export function DrawLineUp(arg1) {
  return window['go']['app']['Bridge']['DrawLineUp'](arg1);
}

export function Enter() {
  return window['go']['app']['Bridge']['Enter']();
}

export function FillRegion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['Bridge']['FillRegion'](arg1, arg2, arg3, arg4, arg5);
}

export function InsertText(arg1) {
  return window['go']['app']['Bridge']['InsertText'](arg1);
}

export function MoveBottom() {
  return window['go']['app']['Bridge']['MoveBottom']();
}

export function MoveDown() {
  return window['go']['app']['Bridge']['MoveDown']();
}

export function MoveEnd() {
  return window['go']['app']['Bridge']['MoveEnd']();
}

export function MoveHome() {
  return window['go']['app']['Bridge']['MoveHome']();
}

export function MoveLeft() {
  return window['go']['app']['Bridge']['MoveLeft']();
}

export function MoveRight() {
  return window['go']['app']['Bridge']['MoveRight']();
}

export function MoveTop() {
  return window['go']['app']['Bridge']['MoveTop']();
}

export function MoveUp() {
  return window['go']['app']['Bridge']['MoveUp']();
}

export function OpenExternalURL(arg1) {
  return window['go']['app']['Bridge']['OpenExternalURL'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['app']['Bridge']['OpenFile'](arg1);
}

export function OpenFileDialog() {
  return window['go']['app']['Bridge']['OpenFileDialog']();
}

export function PasteFromClipboard() {
  return window['go']['app']['Bridge']['PasteFromClipboard']();
}

export function Save() {
  return window['go']['app']['Bridge']['Save']();
}

export function SaveAsDialog() {
  return window['go']['app']['Bridge']['SaveAsDialog']();
}

export function SaveFile(arg1) {
  return window['go']['app']['Bridge']['SaveFile'](arg1);
}

export function SetActiveANSIBGColor(arg1) {
  return window['go']['app']['Bridge']['SetActiveANSIBGColor'](arg1);
}

export function SetActiveANSIColor(arg1) {
  return window['go']['app']['Bridge']['SetActiveANSIColor'](arg1);
}

export function SetActiveANSIFGColor(arg1) {
  return window['go']['app']['Bridge']['SetActiveANSIFGColor'](arg1);
}

export function SetCursor(arg1, arg2) {
  return window['go']['app']['Bridge']['SetCursor'](arg1, arg2);
}

export function SetRegionBGColor(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['Bridge']['SetRegionBGColor'](arg1, arg2, arg3, arg4, arg5);
}

export function SetRegionColor(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['Bridge']['SetRegionColor'](arg1, arg2, arg3, arg4, arg5);
}

export function SetRegionTextStyle(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['Bridge']['SetRegionTextStyle'](arg1, arg2, arg3, arg4, arg5);
}

export function Snapshot() {
  return window['go']['app']['Bridge']['Snapshot']();
}
